backend:
  name: github
  repo: glammysports/sportswear-glammysports
  branch: main # or your default branch
  commit_messages: true

media_folder: "images"  # Where uploaded images will be stored
public_folder: "/images" # How images are referenced in HTML

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
